.class public Lcom/s1243808733/aide/functions/installer/ShellInstall;
.super Ljava/lang/Thread;
.source "ShellInstall.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/s1243808733/aide/functions/installer/ShellInstall$Error;
    }
.end annotation


# instance fields
.field private apkPath:Ljava/lang/String;

.field private isRoot:Z

.field private packageName:Ljava/lang/String;

.field private shizuku:Ljava/io/File;


# direct methods
.method public constructor <init>(Ljava/lang/String;Ljava/lang/String;Z)V
    .registers 4

    .line 38
    invoke-direct {p0}, Ljava/lang/Thread;-><init>()V

    .line 39
    iput-object p1, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->apkPath:Ljava/lang/String;

    .line 40
    iput-boolean p3, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->isRoot:Z

    .line 41
    iput-object p2, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->packageName:Ljava/lang/String;

    return-void
.end method

.method private copyFile(Ljava/lang/String;Ljava/lang/String;)V
    .registers 6
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/lang/Exception;
        }
    .end annotation

    .line 140
    new-instance v0, Ljava/io/FileInputStream;

    invoke-direct {v0, p1}, Ljava/io/FileInputStream;-><init>(Ljava/lang/String;)V

    .line 141
    new-instance p1, Ljava/io/FileOutputStream;

    invoke-direct {p1, p2}, Ljava/io/FileOutputStream;-><init>(Ljava/lang/String;)V

    .line 142
    const/16 p2, 0x1000

    new-array p2, p2, [B

    .line 144
    :goto_e
    invoke-virtual {v0, p2}, Ljava/io/FileInputStream;->read([B)I

    move-result v1

    if-lez v1, :cond_19

    .line 146
    const/4 v2, 0x0

    invoke-virtual {p1, p2, v2, v1}, Ljava/io/FileOutputStream;->write([BII)V

    goto :goto_e

    .line 148
    :cond_19
    invoke-virtual {v0}, Ljava/io/FileInputStream;->close()V

    .line 149
    invoke-virtual {p1}, Ljava/io/FileOutputStream;->close()V

    return-void
.end method


# virtual methods
.method public initShizuku()V
    .registers 7
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/lang/Exception;
        }
    .end annotation

    .line 156
    invoke-static {}, Lcom/s1243808733/aide/application/App;->getApp()Lcom/s1243808733/aide/application/App;

    move-result-object v0

    invoke-virtual {v0}, Lcom/s1243808733/aide/application/App;->getApplicationInfo()Landroid/content/pm/ApplicationInfo;

    move-result-object v0

    invoke-static {v0}, Lcom/s1243808733/util/Utils$$ExternalSyntheticApiModelOutline0;->m(Landroid/content/pm/ApplicationInfo;)Ljava/lang/String;

    move-result-object v0

    .line 157
    new-instance v1, Ljava/io/File;

    const-string v2, "shizuku"

    invoke-direct {v1, v0, v2}, Ljava/io/File;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    iput-object v1, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->shizuku:Ljava/io/File;

    .line 158
    new-instance v1, Ljava/io/File;

    const-string v2, "shizuku.dex"

    invoke-direct {v1, v0, v2}, Ljava/io/File;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    .line 159
    iget-object v0, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->shizuku:Ljava/io/File;

    invoke-virtual {v0}, Ljava/io/File;->exists()Z

    move-result v0

    if-nez v0, :cond_2a

    invoke-virtual {v1}, Ljava/io/File;->exists()Z

    move-result v0

    if-eqz v0, :cond_32

    .line 160
    :cond_2a
    iget-object v0, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->shizuku:Ljava/io/File;

    invoke-virtual {v0}, Ljava/io/File;->delete()Z

    .line 161
    invoke-virtual {v1}, Ljava/io/File;->delete()Z

    .line 164
    :cond_32
    const-string v0, "IyEvc3lzdGVtL2Jpbi9zaApCQVNFRElSPSQoZGlybmFtZSAiJDAiKQpERVg9IiRCQVNFRElSIi9zaGl6dWt1LmRleAoKaWYgWyAhIC1mICIkREVYIiBdOyB0aGVuCiAgZWNobyAiQ2Fubm90IGZpbmQgJERFWCwgcGxlYXNlIGNoZWNrIHRoZSB0dXRvcmlhbCBpbiBTaGl6dWt1IGFwcCIKICBleGl0IDEKZmkKCiMgUmVwbGFjZSAiUEtHIiB3aXRoIHRoZSBhcHBsaWNhdGlvbiBpZCBvZiB5b3VyIHRlcm1pbmFsIGFwcApleHBvcnQgU0hJWlVLVV9BUFBMSUNBVElPTl9JRD0iUEtHIgovc3lzdGVtL2Jpbi9hcHBfcHJvY2VzcyAtRGphdmEuY2xhc3MucGF0aD0iJERFWCIgL3N5c3RlbS9iaW4gLS1uaWNlLW5hbWU9c3VpX3dyYXBwZXIgcmlra2Euc2hpenVrdS5jbWQuU2hpenVrdUNtZCAiJEAi"

    const/4 v2, 0x0

    invoke-static {v0, v2}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B

    move-result-object v0

    .line 165
    new-instance v3, Ljava/lang/String;

    invoke-direct {v3, v0}, Ljava/lang/String;-><init>([B)V

    invoke-static {}, Lcom/s1243808733/aide/application/App;->getApp()Lcom/s1243808733/aide/application/App;

    move-result-object v0

    invoke-virtual {v0}, Lcom/s1243808733/aide/application/App;->getPackageName()Ljava/lang/String;

    move-result-object v0

    const-string v4, "PKG"

    invoke-virtual {v3, v4, v0}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v0

    .line 166
    invoke-virtual {v0}, Ljava/lang/String;->getBytes()[B

    move-result-object v0

    .line 169
    const/4 v3, 0x0

    :try_start_51
    new-instance v4, Ljava/io/FileOutputStream;

    iget-object v5, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->shizuku:Ljava/io/File;

    invoke-direct {v4, v5}, Ljava/io/FileOutputStream;-><init>(Ljava/io/File;)V
    :try_end_58
    .catch Ljava/io/IOException; {:try_start_51 .. :try_end_58} :catch_9f
    .catchall {:try_start_51 .. :try_end_58} :catchall_9d

    .line 170
    :try_start_58
    invoke-virtual {v4, v0}, Ljava/io/FileOutputStream;->write([B)V
    :try_end_5b
    .catch Ljava/io/IOException; {:try_start_58 .. :try_end_5b} :catch_9a
    .catchall {:try_start_58 .. :try_end_5b} :catchall_98

    .line 176
    :try_start_5b
    invoke-virtual {v4}, Ljava/io/FileOutputStream;->close()V
    :try_end_5e
    .catch Ljava/io/IOException; {:try_start_5b .. :try_end_5e} :catch_5f

    goto :goto_60

    .line 179
    :catch_5f
    move-exception v0

    .line 182
    :goto_60
    const-string v0, "ZGV4CjAzNQCTgkhh2nJTjPXYMb5mrxHfGan/qWGS3im8RwAAcAAAAHhWNBIAAAAAAAAAAOxGAAAY\nAQAAcAAAAF4AAADQBAAAPwAAAEgGAAAqAAAAPAkAAK4AAACMCgAAGAAAAPwPAADANAAA/BIAAAAt\nAAACLQAABi0AABUtAAAjLQAAKy0AAEMtAABOLQAAWS0AAF0tAABhLQAAZS0AAGktAABuLQAAiS0A\nAKQtAAD+LQAAWS4AAGMuAABrLgAAbi4AAHIuAACDLgAAii4AAJcuAACgLgAAqi4AALEuAADcLgAA\n3y4AAOMuAADoLgAA7S4AAPsuAAAeLwAAIS8AACUvAAApLwAALi8AADQvAAA7LwAAYC8AAIUvAACl\nLwAAxy8AAOMvAAD9LwAAEjAAAC4wAABDMAAAWTAAAH4wAACUMAAArTAAAMIwAADXMAAADzEAAEgx\nAABrMQAAjDEAAK0xAADGMQAA5DEAAAEyAAAWMgAAMDIAAEQyAABgMgAAazIAAHYyAACDMgAAjjIA\nAJkyAACkMgAArTIAALYyAAC/MgAAyDIAANMyAADeMgAA6TIAAPQyAAD9MgAACDMAABEzAAAcMwAA\nQDMAAGUzAACFMwAAqDMAAMczAADXMwAA7jMAAAU0AAAdNAAANDQAAE40AABmNAAAiTQAAKs0AAC/\nNAAA1DQAAOo0AAAINQAAHDUAADc1AABLNQAAXzUAAHY1AACZNQAAvTUAAN81AAAHNgAAJjYAAD02\nAABRNgAAZzYAAHk2AACLNgAAojYAALM2AADINgAA2TYAAAY3AAAtNwAATzcAAHE3AACTNwAAszcA\nALs3AADENwAAyTcAAPY3AAAsOAAAPDgAAFk4AACAOAAAmjgAAKM4AAC7OAAALTkAAEE5AABUOQAA\nZzkAAG05AABwOQAAdDkAAHk5AAB+OQAAgjkAAIc5AACNOQAAkjkAAJg5AACbOQAAojkAAKY5AACr\nOQAAsDkAALQ5AAC4OQAAwjkAANc5AADsOQAA7zkAAPw5AAAGOgAACzoAABU6AAAdOgAAJzoAADQ6\nAABHOgAAWDoAAF86AABiOgAAajoAAIg6AACUOgAAlzoAAKo6AAC1OgAAxDoAANY6AADdOgAA4DoA\nAOY6AAD4OgAAATsAAAQ7AAAWOwAAIDsAACc7AAAvOwAANDsAADo7AABFOwAASDsAAE87AABSOwAA\nYzsAAG87AAB/OwAAjzsAAJc7AACfOwAArjsAALo7AADLOwAA1zsAAOw7AAD3OwAAATwAAAk8AAAR\nPAAAFDwAAB08AAAnPAAAKjwAAC48AAA3PAAAQTwAAEQ8AABHPAAASjwAAFc8AABdPAAAYzwAAIY8\nAACuPAAA0jwAANw8AADiPAAA7DwAAPI8AAD6PAAABj0AAAs9AAARPQAAJD0AADU9AAA+PQAAST0A\nAFM9AABoPQAAbj0AAH09AACGPQAAkj0AAKQ9AACtPQAAtT0AAMU9AADxPQAA9j0AABo+AABDPgAA\nYz4AAKI+AAC8PgAA2j4AAAQ/AAALPwAAID8AACk/AAAzPwAAPT8AAEw/AAAGQQAADUEAABBBAAAZ\nQQAAIEEAACpBAAA/QQAAUUEAAF5BAABwQQAAg0EAAJJBAAAcAAAAJwAAACgAAAApAAAAKgAAACsA\nAAAsAAAALQAAAC4AAAAvAAAAMAAAADEAAAAyAAAAMwAAADQAAAA1AAAANgAAADcAAAA4AAAAOQAA\nADoAAAA8AAAAPQAAAD4AAAA/AAAAQAAAAEEAAABCAAAAQwAAAEQAAABFAAAARgAAAEcAAABIAAAA\nSQAAAEoAAABLAAAATAAAAE0AAABOAAAATwAAAFAAAABRAAAAUgAAAFMAAABUAAAAVQAAAFYAAABX\nAAAAWAAAAFkAAABaAAAAWwAAAFwAAABdAAAAXgAAAF8AAABgAAAAYQAAAGIAAABjAAAAZAAAAGUA\nAABmAAAAZwAAAGgAAABpAAAAagAAAGsAAABsAAAAbQAAAG4AAABvAAAAcAAAAHEAAAByAAAAcwAA\nAHQAAAB2AAAAdwAAAHgAAAB5AAAAegAAAHsAAAB8AAAAfQAAAH4AAAB/AAAAkAAAAJkAAACfAAAA\noAAAAKEAAACiAAAAHAAAAAAAAAAAAAAAIAAAAAAAAADkKwAAHgAAAAAAAAAALAAAHwAAAAAAAAAI\nLAAAHQAAAAAAAAAQLAAAJAAAAAQAAAAYLAAAIwAAAAcAAAAgLAAAJQAAAAcAAAAoLAAAJQAAAAcA\nAAAwLAAAIgAAAA0AAAAAAAAAJAAAAA0AAAA4LAAAJAAAAA4AAAA4LAAAIgAAAA8AAAAAAAAAIgAA\nABAAAAAAAAAAIgAAABMAAAAAAAAAJAAAAB0AAAAYLAAAJgAAAB0AAABALAAAIgAAACEAAAAAAAAA\nJgAAACwAAABALAAAIgAAADUAAAAAAAAAIgAAADYAAAAAAAAAIgAAADwAAAAAAAAAJAAAADwAAABM\nLAAAJAAAADwAAABULAAAIgAAAEAAAAAAAAAAJAAAAEAAAAA4LAAAJAAAAEAAAABcLAAAJAAAAEAA\nAABkLAAAIwAAAEEAAAAgLAAAJAAAAEEAAAA4LAAAIgAAAEwAAAAAAAAAIgAAAE8AAAAAAAAAIgAA\nAFEAAAAAAAAAkAAAAFgAAAAAAAAAkQAAAFgAAAAgLAAAkgAAAFgAAABsLAAAkwAAAFgAAAB0LAAA\nlAAAAFgAAAB8LAAAlQAAAFgAAACELAAAlAAAAFgAAAAYLAAAlwAAAFgAAACMLAAAlwAAAFgAAACU\nLAAAlAAAAFgAAACcLAAAlAAAAFgAAABMLAAAlQAAAFgAAACkLAAAlAAAAFgAAACsLAAAlAAAAFgA\nAAC8KwAAmAAAAFgAAAC0LAAAlAAAAFgAAAA4LAAAlwAAAFgAAADALAAAlAAAAFgAAABcLAAAlAAA\nAFgAAADILAAAlgAAAFgAAADQLAAAlAAAAFgAAADcLAAAmQAAAFkAAAAAAAAAmgAAAFkAAADkLAAA\nnAAAAFkAAACELAAAmwAAAFkAAADwLAAAmwAAAFkAAABULAAAmwAAAFkAAACkKwAAnQAAAFkAAAD4\nLAAAIwAAAFwAAAAgLAAAJAAAAFwAAABkLAAACQAAAIkAAAAKABQAGAAAABMAFAAYAAAAHAANAKMA\nAAAgAA0AowAAACIAIgCjAAAAIwAAAKMAAAAjAAAArgAAACQAJACjAAAAJQAlAKMAAAAqAA0AowAA\nACoAIQCuAAAAKgBZALIAAAAqAFkAuAAAACoAHwC8AAAAKgAMAMQAAAAqAE0AxgAAACoATQDWAAAA\nKgBNANkAAAAqAAsA3QAAACwAFAAYAAAALAAdAKMAAAAsADYArgAAACwANQCyAAAALQBNAKMAAABC\nADcAwQAAAEIANQDaAAAAQgA3AOwAAABGAEYAFQAAAEYARgAXAAAARgBGABoAAABGAEYAgAAAAEYA\nRgCBAAAARgBGAI8AAABIAEgAFgAAAFQAQACjAAAAVQBdAKMAAABWADUAowAAAFYANgCuAAAAVgBT\nALIAAABXAFkAowAAAFcAWQCuAAAAAQAFAKMAAAABAA8ArgAAAAIABQCqAAAAAwAFAKoAAAAEAAEA\nBgEAAAcAMAASAAAABwAGAKcAAAAHAAcAtQAAAAcACADyAAAACAAhABIAAAAIADcA6wAAAAoAIQAS\nAAAACgA8AMgAAAAKAAIAywAAAAoAGQDSAAAACgAxAPEAAAALACoAEgAAAAsAOwDtAAAADQAmAOAA\nAAANAAsA8wAAAA0ANwAJAQAADQA4AAoBAAAOAAkAqQAAAA8ADADNAAAADwAhAOEAAAAPAAwA5gAA\nAA8AIQDuAAAAEAAwAL0AAAAQAA0A6gAAABAAIQD1AAAAEAAAAPYAAAAQABgA9wAAABAACQD4AAAA\nEAAhAPkAAAAQACIAEAEAABAAMAARAQAAEAAhABIBAAAQADAAEwEAABAANQAUAQAAEAAnABUBAAAR\nAC0AEgAAABIALQASAAAAFAAWALYAAAAXAAoA0AAAABgAAADVAAAAGQA5ANsAAAAaABoA0QAAABoA\nAwDZAAAAGgADAA0BAAAcACcAEgAAABwADgCjAAAAHAAJAKkAAAAcAA4ArgAAABwAAACyAAAAHAAO\nAMYAAAAcAAAA2QAAABwAIQDdAAAAHQAOAKMAAAAdAA4ArgAAAB0AAACyAAAAHQAOAMYAAAAdAAAA\n2QAAAB0AIQDdAAAAHgAhABIAAAAeAAkAqQAAAB4AKQCsAAAAHgA3AOsAAAAgACcAEgAAACAACQCp\nAAAAIAA2ALgAAAAgADYAvAAAACAAIgDEAAAAIAAQANYAAAAhADYAuAAAACEANgC8AAAAIQAiAMQA\nAAAhABAA1gAAACIAIQARAAAAIgAhABIAAAAiACEAsQAAACMAIwASAAAAIwAhAP0AAAAkACEAEQAA\nACQAIQASAAAAJAAhAP0AAAAlACEAEQAAACUAIQASAAAAJQAhAP0AAAAmACEAEgAAACYAJQDeAAAA\nJgAkAN8AAAAnACEAowAAACgAIQCjAAAAKQAjAKMAAAAqACEAEQAAACoAIQCjAAAAKgAhAK4AAAAq\nACMAsgAAACoAEgC4AAAAKgAoALwAAAAqABEAxAAAACsAIQASAAAAKwAWALYAAAArAD0A6AAAACwA\nIQARAAAALAArABIAAAAsAC4AEgAAACwAAAC6AAAALAAhALsAAAAsAAAAwwAAACwAEwDJAAAALAAT\nAMoAAAAsABQAzwAAACwAAAAOAQAALAAsABYBAAAtADMAEgAAAC0AIQCjAAAAMwAwABIAAAAzABgA\nxwAAADQAIQDvAAAANQAEAPQAAAA2ACEAxQAAADYANAAPAQAANwAhAMUAAAA3ADAA8AAAADoAMAAS\nAAAAOwAhAO8AAAA8ACEAEgAAAD0AIQASAAAAPwAyABIAAABAADoAwAAAAEAAAADYAAAAQQAhABIA\nAABBABwAqAAAAEEAHQCoAAAAQQAYAAgBAABCACIAwgAAAEIAGQDUAAAAQgAfANQAAABDACEAEgAA\nAEMAIQAFAQAARAAYAM4AAABKACEAEgAAAEoAOgCmAAAASgA+AAcBAABLABsACAEAAEwANgDXAAAA\nTAAVAOkAAABNADoApgAAAE0AHgDcAAAATQA6APoAAABNAD4ABwEAAE4AFQDMAAAATgAVANMAAABP\nACAAvgAAAFAAFwD7AAAAUQAeANwAAABSACEAEgAAAFMAIgASAAAAUwAhAK0AAABTACEAtAAAAFQA\nMAASAAAAVAA3AOsAAABVADUAEgAAAFUAIwCjAAAAVgAvABIAAABWACEA/QAAAFcAIQASAAAAVwAw\nAKMAAABXADUArgAAAFcANQCyAAAAVwAwALgAAABXADAAvAAAAFcANQDiAAAAAQAAAAEAAAA8AAAA\nAAAAAAAAAAAAAAAAC0MAAAAAAAAbAAAAASYAADwAAACMKwAAAAAAAORFAAAAAAAAAAAAAB0AAAAB\nBgAAPAAAAJQrAAAAAAAAAAAAABdDAAAAAAAAHwAAAAEGAAA8AAAAlCsAAAAAAAD0RQAAAAAAAAAA\nAAAhAAAAAQYAADwAAACUKwAAAAAAAAAAAAAzQwAAAAAAACIAAAAREAAAPAAAAJwrAAAAAAAAAAAA\nAEdDAAAAAAAAIwAAABEQAAA8AAAApCsAAAAAAAAAAAAAXkMAAAAAAAAkAAAAERAAADwAAACkKwAA\nAAAAAAAAAAByQwAAAAAAACUAAAAREAAAPAAAAKQrAAAAAAAAAAAAAIlDAAAAAAAAJwAAAAEGAAA8\nAAAAAAAAAAAAAAAERgAAoEMAAAAAAAAoAAAAAQYAADwAAAAAAAAAAAAAABRGAACoQwAAAAAAACkA\nAAABBgAAPAAAAAAAAAAAAAAAJEYAALBDAAAAAAAAKgAAAAEAAAA8AAAAAAAAAAAAAAA0RgAAuEMA\nAB5FAAArAAAAEQAAADwAAACsKwAAAAAAAGRGAADuQwAAAAAAACwAAAABAAAAPQAAALQrAAAAAAAA\ndEYAAABEAAAAAAAAVAAAABEAAAAIAAAAAAAAAAAAAACMRgAAPkQAAAAAAABWAAAAAQAAAEMAAAAA\nAAAAAAAAAJxGAABRRAAAAAAAAFcAAAABAAAAPAAAAAAAAAAAAAAArEYAAGdEAAAjRQAAHAAAAAEA\nAAA8AAAAvCsAAAAAAAAAAAAAjkQAAAAAAAAeAAAAAQQAAAgAAADEKwAAAAAAALxGAAC2RAAAAAAA\nACAAAAABAAAAPAAAAMwrAAAAAAAAAAAAAMhEAAAAAAAALQAAABEQAAA8AAAA1CsAAAAAAAAAAAAA\n6EQAAAAAAABVAAAAEQAAADwAAADcKwAAAAAAAMxGAAD5RAAAAAAAACYAAAARAAAAHgAAAAAAAAAA\nAAAA3EYAAAxFAAAAAAAAAQABAAEAAAAAAAAABQAAAHEQAgAAAAwAEQAAAAMAAQACAAAAAAAAABkA\nAAA5AgQAEgIRAhoA4wByIBMAAgAMADgACQAgAR0AOAEFAB8AHQARACIAHABwIDEAIAARAAAAAgAB\nAAAAAAAAAAAAAwAAAFQQAwARAAAABgABAAUAAQAAAAAANwAAAHEAHAAAAAwAcQAcAAAADAEaAuMA\nbiAjACAAVFIDABIzEgRyVBQAMhAKAm4QHQABAG4QHgABAAoCOAILAGICAgByICoAEgAMAh8CEwAo\nAhICbhAhAAEAbhAhAAAAEQINAm4QIQABAG4QIQAAACcCAAAIAAAAHgABAAEALwAGAAEABQABAAAA\nAAA3AAAAcQAcAAAADABxABwAAAAMARoC4wBuICMAIABUUgMAEiMSBHJUFAAyEAoCbhAdAAEAbhAe\nAAEACgI4AgsAYgICAHIgKgASAAwCHwITACgCEgJuECEAAQBuECEAAAARAg0CbhAhAAEAbhAhAAAA\nJwIAAAgAAAAeAAEAAQAvAAYAAQAFAAEAAAAAADcAAABxABwAAAAMAHEAHAAAAAwBGgLjAG4gIwAg\nAFRSAwASExIEclQUADIQCgJuEB0AAQBuEB4AAQAKAjgCCwBiAgIAciAqABIADAIfAhMAKAISAm4Q\nIQABAG4QIQAAABECDQJuECEAAQBuECEAAAAnAgAACAAAAB4AAQABAC8ABgABAAUAAQAAAAAAKwAA\nAHEAHAAAAAwAcQAcAAAADAEaAuMAbiAjACAAVFIDABJTEgRyVBQAMhAKAm4QHQABAG4QHgABAAoC\nbhAhAAEAbhAhAAAADwINAm4QIQABAG4QIQAAACcCAAAIAAAAFAABAAEAIwAGAAEABQABAAAAAAAr\nAAAAcQAcAAAADABxABwAAAAMARoC4wBuICMAIABUUgMAEkMSBHJUFAAyEAoCbhAdAAEAbhAeAAEA\nCgJuECEAAQBuECEAAAAPAg0CbhAhAAEAbhAhAAAAJwIAAAgAAAAUAAEAAQAjAAIAAgABAAAAAAAA\nAAYAAABwEH8AAABbAQMADgAGAAEABQABAAAAAAAnAAAAcQAcAAAADABxABwAAAAMARoC4wBuICMA\nIABUUgMAEmMSBHJUFAAyEAoCbhAdAAEAbhAhAAEAbhAhAAAADgANAm4QIQABAG4QIQAAACcCAAAI\nAAAAEAABAAEAHwABAAEAAAAAAAAAAAABAAAAEQAAAAkABQAFAAAAAAAAAGUAAAASIBIBEhIaA+QA\nMgVHABIwMgUnABMAEScyBRAAFABGVE5fMgUHAG9YCgBUdgoFDwVuICUANwAPAm4gGwA2AG4QHgAG\nAG4QHgAGAG4QHwAGAG4QHgAGAG4QJAAHAA8CbiAbADYAbhAeAAYACgVuEB4ABgAKBzgHCwBiBwEA\nciAqAGcADAYHYR8BCgAHRh8GJgBuMFoAVgEPAm4gGwA2AG4QHgAGAAoFOAULAGIFAQByICoAZQAM\nBQdRHwEKAAdFHwUmAG4gWQAVAA8CAAACAAEAAwAAAAAAAAAJAAAAcBAJAAEAGgDkAG4wQQARAA4A\nAAACAAEAAAAAAAAAAAADAAAAVBAEABEAAAAGAAEABQABAAAAAAAvAAAAcQAcAAAADABxABwAAAAM\nARoC5QBuICMAIABUUgQAEwMQABIEclQUADIQCgJuEB0AAQBuEB4AAQAKAjgCAwASFG4QIQABAG4Q\nIQAAAA8EDQJuECEAAQBuECEAAAAnAgAACAAAABUAAQABACcABgABAAUAAQAAAAAALwAAAHEAHAAA\nAAwAcQAcAAAADAEaAuUAbiAjACAAVFIEABMDEQASBHJUFAAyEAoCbhAdAAEAbhAeAAEACgI4AgMA\nEhRuECEAAQBuECEAAAAPBA0CbhAhAAEAbhAhAAAAJwIAAAgAAAAVAAEAAQAnAAcABAAFAAEAAAAA\nADkAAABxABwAAAAMAHEAHAAAAAwBGgLlAG4gIwAgAG4gJgBAAG4gJgBQAG4gJQBgAFQ0BAATBQgA\nEgZyVhQAVBAKBG4QHQABAG4QIAABAAwEcRABAAQADARuECEAAQBuECEAAAARBA0EbhAhAAEAbhAh\nAAAAJwQAAAgAAAAiAAEAAQAxAAIAAgABAAAAAAAAAAYAAABwEH8AAABbAQQADgAGAAIABQABAAAA\nAAArAAAAcQAcAAAADABxABwAAAAMARoC5QBuICMAIABuICIAUABURQQAEwIPABIDclMUACUQCgVu\nEB0AAQBuECEAAQBuECEAAAAOAA0FbhAhAAEAbhAhAAAAJwUAAAgAAAAUAAEAAQAjAAEAAAABAAAA\nAAAAAAgAAAAiACIAcBBOAAAAaQAFAA4AAQABAAEAAAAAAAAABAAAAHAQfwAAAA4AAgABAAIAAAAI\nKwAABQAAABIAcSBjAAAADgAAAAMAAwABAAAAAAAAAAgAAABwEH8AAABZAQYAWQIHAA4AAwABAAIA\nAAAMKwAACAAAAFIgBgBSIQcAcSBhABAADgABAAAAAQAAAAAAAAAIAAAAIgAkAHAQUwAAAGkACAAO\nAAEAAQABAAAAAAAAAAQAAABwEH8AAAAOAAEAAQAAAAAAECsAAAQAAABxAGAAAAAOAAEAAAABAAAA\nAAAAAAgAAAAiACUAcBBWAAAAaQAJAA4AAQABAAEAAAAAAAAABAAAAHAQfwAAAA4AAQABAAAAAAAQ\nKwAABAAAAHEAXwAAAA4AAQABAAEAAAAAAAAABAAAAHAQPwAAAA4ABAACAAMAAAAUKwAAJwAAABoA\nAgES8W4wDQADARoAAwFuMA0AAwEaAP4AbjANAAMBGgAAAW4gDgADABoA/wASAW4wDAADAQoAagAM\nABoAAQFuMAwAAwEKA2oDDQAOAAAABQADAAMAAAAdKwAAJAAAABoABAESAW4wDAAEAQoEOAQDACgC\nEvFxABkAAAAMBHEAFwAAAAwAMwQGAHEgYQATACgLYgQTACIAIwBwMFAAMAFuIBEABAAOAAMAAgAC\nAAAAIysAAAYAAAAiACwAcCBpACAAEQACAAIAAAAAACkrAAADAAAAIxFbABEBAAABAAEAAQAAAAAA\nAAAEAAAAcBB/AAAADgACAAEAAAAAAAAAAAACAAAAEgAPAAMAAQACAAEAAAAAAA4AAABUIBUAchA7\nAAAACgAPAA0AIgE/AHAggQABACcBAAAAAAYAAQABARYHAwABAAIAAQAAAAAADgAAAFQgFQByED0A\nAAAKAA8ADQAiAT8AcCCBAAEAJwEAAAAABgABAAEBFgcDAAEAAgABAAAAAAATAAAAIgARAFQhFQBy\nEDoAAQAMAXAgKAAQABEADQAiAT8AcCCBAAEAJwEAAAAAAAALAAEAAQEWDAMAAQACAAEAAAAAABwA\nAABUIBcAOQAXACIAEQBUIRUAchA5AAEADAFwICgAEABbIBcAKAgNACIBPwBwIIEAAQAnAVQgFwAR\nAAQAAAANAAEAAQEWEgMAAQACAAEAAAAAABwAAABUIBYAOQAXACIAEgBUIRUAchA8AAEADAFwICkA\nEABbIBYAKAgNACIBPwBwIIEAAQAnAVQgFgARAAQAAAANAAEAAQEWEgEAAAABAAAAAAAAAAgAAAAi\nACsAcBBlAAAAaQAUAA4AAgACAAEAAAAAAAAADgAAAHAQgAAAAG4QIAABAAwBcRABAAEADAFbARUA\nDgACAAIAAQAAAAAAAAAGAAAAcBCAAAAAWwEVAA4AAwABAAIAAQAAAAAADQAAAFQgFQByED4AAAAO\nAA0AIgE/AHAggQABACcBAAAAAAAABQABAAEBFgYDAAMAAgAAAAAAAAAKAAAAVAIVAHIQFgACAAwC\nbiAnACEADgACAAAAAgAAAAAAAAANAAAAYgALADgAAwARACIAOgAaAbAAcCB9ABAAJwAAAAUAAwAE\nAAEALisAABUAAAAiACwAcQBkAAAADAFyQEwAIUMMAnAgagAgABEADQIiAz8AcCCBACMAJwMAAAAA\nAAANAAEAAQEWDgIAAAACAAAAAAAAACwAAAAiACYAcBBYAAAAaQAOAGIABQBpAA8AIgBSAHAQnQAA\nAGkAEAAiAFIAcBCdAAAAaQARACIAUgBwEJ0AAABpABIAIgALAHEAFwAAAAwBcCAQABAAaQATAA4A\nAgAAAAEAAAAAAAAAFwAAAGIAEQByEJUAAAAMAHIQkgAAAAoBOAEMAHIQkwAAAAwBHwEnAHIQWwAB\nACjxDgAAAAIAAAABAAAAAAAAABcAAABiABAAchCVAAAADAByEJIAAAAKATgBDAByEJMAAAAMAR8B\nKAByEFwAAQAo8Q4AAAAEAAIAAwAAAAAAAAAXAAAAYgASAHIQlQAAAAwAchCSAAAACgE4AQwAchCT\nAAAADAEfASkAcjBdACEDKPEOAAAACAACAAUABAA2KwAApgAAABoAqwAaAYwAYgIKADNiAwAOADkG\nHwASBmkGCgBpBgsAcQAZAAAADAZxABcAAAAMBzN2BwBxAF8AAAApAIgAYgYTAGIHCQBuIBEAdgAp\nAH8AEgM4AgcAYgQPAHIwFQBCA2kGCgAaAuUAciATACYADAQ4BAkAIEUhADgFBQAfBCEAKAYiBCAA\ncCBDAGQAaQQLAGIGCgBiBA8AcjASAEYDKARxIC8AAQBxABwAAAAMBnEAHAAAAAwEbiAjACYAYgIO\nAB8CHgBxEJsAAgBuICcAJgBuICUAdgBiBwoAEwIOAHJTFAAnRgoHbhAdAAQAbhAhAAQAbhAhAAYA\ncSAvAAEAKBENB24QIQAEAG4QIQAGACcHDQZxEC4ABgAMBnEgMABhAHEAGQAAAAwGcQAXAAAADAcz\ndgYAcQBgAAAAKAhiBhMAYgcIAG4gEQB2AA4ASAAAAAcAAQBTAAAACAADAFsAAAAbAAYAdgAAABIA\nAwADAFAAiAEAgAEAAAACAAIAAQAAAAAAAAAGAAAAcBB/AAAAWwEYAA4AAwABAAIAAQBKKwAAFgAA\nAFQgGAASASMRXQByIJcAEAAMAB8AXQBxEKoAAAAOAA0AIgE/AHAggQABACcBAwAAAAsAAQABATsP\nBgAFAAUAAQBOKwAANQAAABIQMwIvABoChQBxEKwAAgBuECAAAwAMAjgCIwBUEyMAcSBjADIAKBwi\nAkEAcBCEAAIAGgOEAG4ghgAyAFQTIwBuIIYAMgAaAwMAbiCGADIAbhCHAAIADAJxEKgAAgAPAG9V\nCgAhQwoCDwIAAA4AAAAFAAEAAQAUAAIAAgABAAAAAAAAAAYAAABbASMAcBAJAAAADgACAAIAAQAA\nAAAAAAAGAAAAWwEkAHAQfwAAAA4AAwADAAIAAQBbKwAAGAAAAGIBEgByIJYAAQA5Ag0AVAEkAHEQ\nqQABACgLDQFuEH4AAQAoBhoBgwBxEKgAAQAOAAcAAAAFAAEAAQE7DQQABAABAAAAAAAAAAoAAABw\nEIsAAABbASUAWwImAFsDJwAOAAUAAQAEAAEAAAAAACUAAAATAAAgIwBaAFRBJQBuIHgAAQAKARLy\nMiESAFRCJgASA25AegACE1RBJgBuEHkAAQAo7A0AbhB3AAAAVEAnADgABQBuEKAAAAAOAAAABAAA\nABQAAQABATQZAQABAAEAAAAAAAAABAAAAHAQfwAAAA4ABAABAAIAAAAAAAAAJQAAAGIAGQAiAUEA\ncBCEAAEAGgKeAG4ghgAhAG4ghgAxABoDAQBuIIYAMQBuEIcAAQAMA24gfAAwAGIDGQBuEHsAAwAS\nE3EQiAADAA4AAAAKAAEABAACAAAAAAAjAQAAYwApABoBDAAaAo4AEgMSBDgAngAiAEoAcBCOAAAA\ncQCKAAAADAVyEJoABQAMBXIQnAAFAAwFchCSAAUACgY4BiwAchCTAAUADAYfBk4AIgdBAHAQhAAH\nAHIQmAAGAAwIHwhAAG4ghgCHABoIEwBuIIYAhwByEJkABgAMBh8GQABuIIYAZwBuEIcABwAMBm4g\njwBgACjRI0VdAG4gkABQAAwAHwBdACIFMwAaBgAAcCB1AGUAbhB2AAUADAUiBkEAcBCEAAYAGge3\nAG4ghgB2AG4ghgBWAG4QhwAGAAwGcRCsAAYAIgZBAHAQhAAGABoHvwBuIIYAdgBxEJEAAAAMB24g\nhgB2AG4QhwAGAAwGcRCsAAYAIgZBAHAQhAAGAG4ghgAmAEYCCQRuIIYAJgBuIIYAFgBuEIcABgAM\nAXEQrAABAHEwYgAJBQwAKBwiAEEAcBCEAAAAbiCGACAARgIJBG4ghgAgAG4ghgAQAG4QhwAAAAwA\ncRCsAAAAcTBiADkDDABuEG8AAAAMAW4QbgAAAAwCbhBwAAAADAUiBlMAEidwIJ4AdgAiB1YAYggb\nAHBApQAXaG4QjAAHACIBVgBiBxsAcEClACFnbhCMAAEAIgFWAGICGgBwQKUAITVuEIwAAQBuEHEA\nAAAKAG4QnwAGACIBQQBwEIQAAQAaAhkAbiCGACEARgkJBG4ghgCRABoJAgBuIIYAkQBuIIUAAQBu\nEIcAAQAMCXEQrAAJAHEQiAAAAA4ADQluEI0ACQAMCXEQqAAJAA4AAAAAAAAAAgABAAoAAADDAAEA\nAQCaAgoAAQACAAEAZSsAADIBAAAhkBoBCwE5AAgAYgkbAG4gfAAZAA4AIgBKAHAQjgAAACGSEgMB\nNDUkhgBGBQkEbhCDAAUAEvZuEIMABQAKBxIYLAfcAAAAKQBZABoHBwBuIIIAdQAKBzkHAwAoTxJ2\nKE0aBwYAbiCCAHUACgc5BwMAKEQSZihCGgcEAG4gggB1AAoHOQcDACg5ElYoNxoHBQBuIIIAdQAK\nBzkHAwAoLhJGKCwaBwsAbiCCAHUACgc5BwMAKCMSNighGgcKAG4gggB1AAoHOQcDACgYEiYoFhoH\nCQBuIIIAdQAKBzkHAwAoDQGGKAsaBwgAbiCCAHUACgc5BwMAKAIBNisGogAAAG4gjwBQACgOaggo\nACgLYgkbABoADgBuIHwACQAOAGoIKQDYBAQBKIFiCRsAbiB8ABkADgBxACwAAAAKCRMB0AczGQUA\nGgmzACgaGgmKAHEQiQAJAAwJcRAtAAkACgE5AQoAGgGCAG4gggCRAAoBOAEHABoBiwBxEKgAAQBx\nABoAAAAaAYcAcRCsAAEAGgEhAHEQrAABABoBDQBxEKwAAQAaAQ8AcRCsAAEAGgEQAHEQrAABACIB\nLQBwIHMAAQBiAAoAYgAQAHIglAAQAHEQqwAJACgQDQliABsAcRAuAAkADAluIHwAkAAaCRsAcRCo\nAAkAcQAYAAAADgAAAggA2wUAAOAFAADjBQAA6QUAALLVOCDhBHVP4t+JZziDkWdSAAAARwAAADwA\nAAAxAAAAJgAAABsAAAAQAAAABQAAAAABCAAAAAAAFwAAABIAAAASAAAACgAAABIAAAAXAAAABwAA\nAAoAAADlAAAAAwABAAEA6QEDAAEAAgADAHUrAABlAAAAYwAMABIBOAADACgNcQBkAAAADAByEEoA\nAAAKAGoADAA4AAQAARAoAhLwOQAGAHEQqQACACg1YwAMADgABAABECgRYwANADgABAASECgLcQBk\nAAAADAByEEkAAAAKAGoADQA4AAgAGgKDAHEQqAACACgXGgCIAHEQrAAAACIAVQBwIKMAIABiAhIA\nciCUAAIAcQBkAAAADAJyIEsAEgAOAA0CIgA/AHAggQAgACcADQIiAD8AcCCBACAAJwANAiIAPwBw\nIIEAIAAnAAAABgAAAAoAAQAnAAAACgAEAEgAAAAHAAcAAwEWXgEWVwEWUAAADwABAAwAAAAAAAAA\nZQAAACIAVABwIKEA4AAaAaUAcRArAAEADAFgAgAAEwMaADQyBwBxEAMAAQAMASgFcRAAAAEADAEH\nEiIBCgBwEAsAAQAaA68AbjAPADEAIgAHABoD/ABwIAUAMAAVAwAEbiAGADAADAAVAwAQbiAGADAA\nDAAVAwgAbiAGADAADAAaA7kAbjAIADABDAAaAYYAcSAHABAADAUaAI0AcRCsAAAAEgMSBhIHEggS\nCRIKEgsSDHEALAAAAAoAFAGghgEAkw0AAQfkeAwEAAIADgAAAAQAAQACAAAAAAAAACYAAABjACgA\nOQADAA4AYgAbACIBQQBwEIQAAQAaAp4AbiCGACEAbiCGADEAGgMBAG4ghgAxAG4QhwABAAwDbiB8\nADAAYgMbAG4QewADAA4AAQAdAAEASgABAA4AAQEAARwOS0sAAQIAALMAAQEADi0AAQEADgABAwAA\nAO9aAAECAAD+ARsPlgESDwEcDzwBKw8AAQBZAAEEAAAAAFk8ASQPSwABAgAADngtWmkAAQEAWWkB\niAEPaQFFDy1aAAEBAA4BFw9LARoP4VqWWi1aLVoAAAAAAQAAAEUAAAABAAAADgAAAAEAAAAMAAAA\nAQAAAD4AAAABAAAAFAAAAAEAAAAVAAAAAQAAAB0AAAABAAAAHwAAAAEAAAAhAAAAAQAAACgAAAAB\nAAAAKQAAAAsAAAAFAEAABwBAAA0AQAAAAAAABgAKAAAAAAACAAAAQAAAAAIAAABAAEAAAQAAAFoA\nAAABAAAADQAAAAEAAAAAAAAAAgAAAAcAOAACAAAAQAAKAAEAAABAAAAAAwAAAF0AXQBAAAAAAQAA\nABAAAAABAAAAPAAAAAEAAABEAAAAAQAAAFwAAAACAAAAAAAAAAIAAAAAAAoAAQAAAAoAAAACAAAA\nDAAAAAIAAAANAEAAAgAAAA4AQAABAAAADwAAAAIAAAAQAAAAAQAAABMAAAADAAAANQA2AFMAAAAC\nAAAAQAANAAEAAABNAAAAAwAAAFoAAAAAAAAAAQAAAF0AAAAEAAAAAAAQABAAAAABAAAAOAAAAAIA\nAABAAFkAAAACIF0ADSBleGl0ZWQgd2l0aCAADCwgaXMgY29ycmVjdAAGLS1oZWxwABYtLXByZXNl\ncnZlLWVudmlyb25tZW50AAktLXZlcmJvc2UACS0tdmVyc2lvbgACLWgAAi1tAAItcAACLXYAAy4u\nLgAZMS4gU2hpenVrdSBhcHAgaXMgaW5zdGFsbAAZMTEuMy4wLnI1NDcuYjcxMTJjOCAoNTQ3KQBY\nMi4gSWYgeW91ciBzeXN0ZW0gb3IgeW91IGFyZSB1c2luZyB0aGlyZC1wYXJ0eSB0b29scyB0byBw\ncmV2ZW50IFNoaXp1a3UgYXBwIGZyb20gcnVubmluZwBZMy4gSWYgdGhpcyB0ZXJtaW5hbCBhcHAg\naXMgaW4gZm9yZWdyb3VuZCAoQW5kcm9pZCAxMCBiYWNrZ3JvdW5kIHN0YXJ0IGFjdGl2aXR5IGxp\nbWl0YXRpb24ACDxjbGluaXQ+AAY8aW5pdD4AAT0AAj47AA9BTk5PVEFUSU9OX1RZUEUABUNMQVNT\nAAtDT05TVFJVQ1RPUgAHQ1JFQVRPUgAIQ29tbWFuZCAABUZJRUxEAClGYWlsZWQgdG8gcmVxdWVz\ndCBiaW5kZXIgZnJvbSBTaGl6dWt1IGFwcAABSQACSUwAA0lMSQADSUxMAAxJTExMTExMSUlMTEkA\nIUlmIHRoaXMgbmV2ZXIgZW5kcywgcGxlYXNlIGNoZWNrOgABTAACTEkAAkxMAANMTEwABExMTEwA\nBUxhL2E7ACNMYW5kcm9pZC9hcHAvQWN0aXZpdHlNYW5hZ2VyTmF0aXZlOwAjTGFuZHJvaWQvYXBw\nL0lBY3Rpdml0eU1hbmFnZXIkU3R1YjsAHkxhbmRyb2lkL2FwcC9JQWN0aXZpdHlNYW5hZ2VyOwAg\nTGFuZHJvaWQvYXBwL0lBcHBsaWNhdGlvblRocmVhZDsAGkxhbmRyb2lkL2FwcC9Qcm9maWxlcklu\nZm87ABhMYW5kcm9pZC9jb250ZW50L0ludGVudDsAE0xhbmRyb2lkL29zL0JpbmRlcjsAGkxhbmRy\nb2lkL29zL0J1aWxkJFZFUlNJT047ABNMYW5kcm9pZC9vcy9CdW5kbGU7ABRMYW5kcm9pZC9vcy9I\nYW5kbGVyOwAjTGFuZHJvaWQvb3MvSUJpbmRlciREZWF0aFJlY2lwaWVudDsAFExhbmRyb2lkL29z\nL0lCaW5kZXI7ABdMYW5kcm9pZC9vcy9JSW50ZXJmYWNlOwATTGFuZHJvaWQvb3MvTG9vcGVyOwAT\nTGFuZHJvaWQvb3MvUGFyY2VsOwA2TGFuZHJvaWQvb3MvUGFyY2VsRmlsZURlc2NyaXB0b3IkQXV0\nb0Nsb3NlSW5wdXRTdHJlYW07ADdMYW5kcm9pZC9vcy9QYXJjZWxGaWxlRGVzY3JpcHRvciRBdXRv\nQ2xvc2VPdXRwdXRTdHJlYW07ACFMYW5kcm9pZC9vcy9QYXJjZWxGaWxlRGVzY3JpcHRvcjsAH0xh\nbmRyb2lkL29zL1BhcmNlbGFibGUkQ3JlYXRvcjsAH0xhbmRyb2lkL29zL1BhcmNlbGFibGUkQ3Jl\nYXRvcjwAF0xhbmRyb2lkL29zL1BhcmNlbGFibGU7ABxMYW5kcm9pZC9vcy9SZW1vdGVFeGNlcHRp\nb247ABtMYW5kcm9pZC9vcy9TZXJ2aWNlTWFuYWdlcjsAE0xhbmRyb2lkL3N5c3RlbS9PczsAGExh\nbmRyb2lkL3RleHQvVGV4dFV0aWxzOwASTGFuZHJvaWQvdXRpbC9Mb2c7ABpMYW5kcm9pZHgvYW5u\nb3RhdGlvbi9LZWVwOwAJTGIvYS9hL2E7AAlMYi9hL2EvYjsAC0xiL2EvYS9jJGE7AAlMYi9hL2Ev\nYzsACUxiL2EvYS9kOwAJTGIvYS9hL2U7AAdMYy9hL2E7AAdMYy9hL2I7AAdMYy9hL2M7AAdMYy9h\nL2Q7AAlMYy9hL2UkYTsACUxjL2EvZSRiOwAJTGMvYS9lJGM7AAlMYy9hL2UkZDsAB0xjL2EvZTsA\nCUxjL2EvZiRhOwAHTGMvYS9mOwAJTGMvYS9nL2E7ACJMZGFsdmlrL2Fubm90YXRpb24vRW5jbG9z\naW5nQ2xhc3M7ACNMZGFsdmlrL2Fubm90YXRpb24vRW5jbG9zaW5nTWV0aG9kOwAeTGRhbHZpay9h\nbm5vdGF0aW9uL0lubmVyQ2xhc3M7ACFMZGFsdmlrL2Fubm90YXRpb24vTWVtYmVyQ2xhc3NlczsA\nHUxkYWx2aWsvYW5ub3RhdGlvbi9TaWduYXR1cmU7AA5MamF2YS9pby9GaWxlOwAVTGphdmEvaW8v\nSU9FeGNlcHRpb247ABVMamF2YS9pby9JbnB1dFN0cmVhbTsAFkxqYXZhL2lvL091dHB1dFN0cmVh\nbTsAFUxqYXZhL2lvL1ByaW50U3RyZWFtOwAYTGphdmEvbGFuZy9DaGFyU2VxdWVuY2U7ABZMamF2\nYS9sYW5nL0RlcHJlY2F0ZWQ7ACFMamF2YS9sYW5nL0lsbGVnYWxTdGF0ZUV4Y2VwdGlvbjsAIExq\nYXZhL2xhbmcvSW50ZXJydXB0ZWRFeGNlcHRpb247ABJMamF2YS9sYW5nL09iamVjdDsAE0xqYXZh\nL2xhbmcvUHJvY2VzczsAFExqYXZhL2xhbmcvUnVubmFibGU7ABxMamF2YS9sYW5nL1J1bnRpbWVF\neGNlcHRpb247ABJMamF2YS9sYW5nL1N0cmluZzsAGUxqYXZhL2xhbmcvU3RyaW5nQnVpbGRlcjsA\nEkxqYXZhL2xhbmcvU3lzdGVtOwASTGphdmEvbGFuZy9UaHJlYWQ7ABVMamF2YS9sYW5nL1Rocm93\nYWJsZTsAIUxqYXZhL2xhbmcvYW5ub3RhdGlvbi9Bbm5vdGF0aW9uOwAiTGphdmEvbGFuZy9hbm5v\ndGF0aW9uL0VsZW1lbnRUeXBlOwAgTGphdmEvbGFuZy9hbm5vdGF0aW9uL1JldGVudGlvbjsAJkxq\nYXZhL2xhbmcvYW5ub3RhdGlvbi9SZXRlbnRpb25Qb2xpY3k7AB1MamF2YS9sYW5nL2Fubm90YXRp\nb24vVGFyZ2V0OwAVTGphdmEvdXRpbC9BcnJheUxpc3Q7ABJMamF2YS91dGlsL0FycmF5czsAFExq\nYXZhL3V0aWwvSXRlcmF0b3I7ABBMamF2YS91dGlsL0xpc3Q7ABBMamF2YS91dGlsL0xpc3Q8ABVM\namF2YS91dGlsL01hcCRFbnRyeTsAD0xqYXZhL3V0aWwvTWFwOwATTGphdmEvdXRpbC9PYmplY3Rz\nOwAPTGphdmEvdXRpbC9TZXQ7ACtMamF2YS91dGlsL2NvbmN1cnJlbnQvQ29weU9uV3JpdGVBcnJh\neUxpc3Q7ACVMamF2YS91dGlsL2NvbmN1cnJlbnQvQ291bnREb3duTGF0Y2g7ACBMcmlra2Evc2hp\nenVrdS9jbWQvU2hpenVrdUNtZCRhOwAgTHJpa2thL3NoaXp1a3UvY21kL1NoaXp1a3VDbWQkYjsA\nIExyaWtrYS9zaGl6dWt1L2NtZC9TaGl6dWt1Q21kJGM7AB5Mcmlra2Evc2hpenVrdS9jbWQvU2hp\nenVrdUNtZDsABk1FVEhPRAAHUEFDS0FHRQADUEtHACtQZXJtaXNzaW9uIGRlbmllZCwgcGxlYXNl\nIGNoZWNrIFNoaXp1a3UgYXBwADRQbGVhc2UgY2hlY2sgaWYgdGhlIGN1cnJlbnQgU0hJWlVLVV9B\nUFBMSUNBVElPTl9JRCwgAA5SZWNlaXZlZCByZXBseQAbUmVxdWVzdCBiaW5kZXIgZnJvbSBTaGl6\ndWt1ACVSZXF1ZXN0aW5nIGJpbmRlciBmcm9tIFNoaXp1a3UgYXBwLi4uABhSZXF1ZXN0aW5nIHBl\ncm1pc3Npb24uLi4AB1NES19JTlQAFlNISVpVS1VfQVBQTElDQVRJT05fSUQAcFNISVpVS1VfQVBQ\nTElDQVRJT05fSUQgaXMgbm90IHNldCwgc2V0IHRoaXMgZW52aXJvbm1lbnQgdmFyaWFibGUgdG8g\ndGhlIGlkIG9mIGN1cnJlbnQgYXBwbGljYXRpb24gKHBhY2thZ2UgbmFtZSkAElNoaXp1a3VBcHBs\naWNhdGlvbgARU3RhcnQgYWN0aXZpdHkuLi4AEVN0YXJ0aW5nIGNvbW1hbmQgAARUWVBFAAFWAAJW\nSQADVklJAANWSUwAAlZMAANWTEkABFZMSUkAA1ZMTAAEVkxMTAABWgAFWklMTEkAAlpMAANaTEkA\nA1pMWgACWyAAAltCAAhbTGMvYS9mOwATW0xqYXZhL2xhbmcvT2JqZWN0OwATW0xqYXZhL2xhbmcv\nU3RyaW5nOwABYQALYWNjZXNzRmxhZ3MACGFjdGl2aXR5AANhZGQACGFkZEZsYWdzAAZhcHBlbmQA\nCGFzQmluZGVyAAthc0ludGVyZmFjZQARYXR0YWNoQXBwbGljYXRpb24AD2F0dGFjaEludGVyZmFj\nZQAFYXdhaXQAAWIABmJpbmRlcgAcYmluZGVyIGhhdmVuJ3QgYmVlbiByZWNlaXZlZAAKYmluZGVy\nRGllZAABYwARY29tLmFuZHJvaWQuc2hlbGwACWNvdW50RG93bgANY3JlYXRlQ2hvb3NlcgAQY3Jl\nYXRlRnJvbVBhcmNlbAAFY3dkOiAAAWQABGRhdGEAEGRlc2NyaWJlQ29udGVudHMAB2Rlc3Ryb3kA\nAWUAEGVuZm9yY2VJbnRlcmZhY2UACGVudHJ5U2V0AAVlbnY6IAAGZXF1YWxzAANlcnIABGV4aXQA\nCWV4aXRWYWx1ZQABZgAFZmx1c2gAAWcAD2dldEFic29sdXRlUGF0aAAKZ2V0Qm9vbGVhbgAOZ2V0\nRXJyb3JTdHJlYW0ADmdldElucHV0U3RyZWFtAAZnZXRJbnQABmdldEtleQANZ2V0TWFpbkxvb3Bl\ncgAKZ2V0TWVzc2FnZQAPZ2V0T3V0cHV0U3RyZWFtAApnZXRTZXJ2aWNlABNnZXRTdGFja1RyYWNl\nU3RyaW5nAAlnZXRTdHJpbmcACGdldFZhbHVlAAZnZXRlbnYABmdldHVpZAABaAAHaGFzTmV4dAAI\naGFzaENvZGUAAWkAAmluAAdpc0VtcHR5AAhpdGVyYXRvcgABagABawABbAALbGlua1RvRGVhdGgA\nBGxvb3AABG1haW4AIW1vZS5zaGl6dWt1LnNlcnZlci5JUmVtb3RlUHJvY2VzcwAmbW9lLnNoaXp1\na3Uuc2VydmVyLklTaGl6dWt1QXBwbGljYXRpb24AIm1vZS5zaGl6dWt1LnNlcnZlci5JU2hpenVr\ndVNlcnZpY2UACG15TG9vcGVyAARuYW1lAAhuZXdBcnJheQAEbmV4dAAGb2J0YWluAApvblRyYW5z\nYWN0AANvdXQABHBvc3QAEXByZXBhcmVNYWluTG9vcGVyAA9wcmludFN0YWNrVHJhY2UAB3ByaW50\nbG4ACXB1dEJpbmRlcgAIcHV0RXh0cmEAE3F1ZXJ5TG9jYWxJbnRlcmZhY2UABHJlYWQADXJlYWRF\neGNlcHRpb24AB3JlYWRJbnQACnJlYWRTdHJpbmcAEHJlYWRTdHJvbmdCaW5kZXIAB3JlY3ljbGUA\nBnJlbW92ZQAOcmVxdWlyZU5vbk51bGwAKnJpa2thLnNoaXp1a3UuaW50ZW50LmFjdGlvbi5SRVFV\nRVNUX0JJTkRFUgADcnVuACJzaGl6dWt1OmF0dGFjaC1yZXBseS1wYXRjaC12ZXJzaW9uACdzaGl6\ndWt1OmF0dGFjaC1yZXBseS1wZXJtaXNzaW9uLWdyYW50ZWQAHnNoaXp1a3U6YXR0YWNoLXJlcGx5\nLXNlY29udGV4dAA9c2hpenVrdTphdHRhY2gtcmVwbHktc2hvdWxkLXNob3ctcmVxdWVzdC1wZXJt\naXNzaW9uLXJhdGlvbmFsZQAYc2hpenVrdTphdHRhY2gtcmVwbHktdWlkABxzaGl6dWt1OmF0dGFj\naC1yZXBseS12ZXJzaW9uAChzaGl6dWt1OnJlcXVlc3QtcGVybWlzc2lvbi1yZXBseS1hbGxvd2Vk\nAAVzdGFydAATc3RhcnRBY3Rpdml0eUFzVXNlcgAHdG9BcnJheQAIdG9TdHJpbmcACHRyYW5zYWN0\nAA11bmxpbmtUb0RlYXRoALcDdXNhZ2U6IHNoaXp1a3UgW09QVElPTl0uLi4gW0NNRF0uLi4KUnVu\nIGNvbW1hbmQgdGhyb3VnaCBTaGl6dWt1LgoKT3B0aW9uczoKLWgsIC0taGVscCAgICAgICAgICAg\nICAgIHByaW50IHRoaXMgaGVscAotdiwgLS12ZXJzaW9uICAgICAgICAgICAgcHJpbnQgdGhlIHZl\ncnNpb24gb2YgdGhlIHNoaXp1a3UgdG9vbAotLXZlcmJvc2UgICAgICAgICAgICAgICAgcHJpbnQg\nbW9yZSBtZXNzYWdlcwotbSwgLXAsCi0tcHJlc2VydmUtZW52aXJvbm1lbnQgICBwcmVzZXJ2ZSB0\naGUgZW50aXJlIGVudmlyb25tZW50CgpUaGlzIGZpbGUgY2FuIGJlIHVzZWQgaW4gYWRiIHNoZWxs\nIG9yIHRlcm1pbmFsIGFwcHMuCkZvciB0ZXJtaW5hbCBhcHBzLCB0aGUgZW52aXJvbm1lbnQgdmFy\naWFibGUgU0hJWlVLVV9BUFBMSUNBVElPTl9JRCBuZWVkcyB0byBiZSBzZXQgdG8gdGhlIGZpcnN0\nLgAFdmFsdWUAAXcAB3dhaXRGb3IABXdyaXRlAAh3cml0ZUludAATd3JpdGVJbnRlcmZhY2VUb2tl\nbgAQd3JpdGVOb0V4Y2VwdGlvbgALd3JpdGVTdHJpbmcAEHdyaXRlU3RyaW5nQXJyYXkAEXdyaXRl\nU3Ryb25nQmluZGVyAA13cml0ZVRvUGFyY2VsAIgBfn5SOHsiY29tcGlsYXRpb24tbW9kZSI6InJl\nbGVhc2UiLCJoYXMtY2hlY2tzdW1zIjpmYWxzZSwibWluLWFwaSI6MjMsInBnLW1hcC1pZCI6ImEw\nODc4NmYiLCJyOC1tb2RlIjoiY29tcGF0aWJpbGl0eSIsInZlcnNpb24iOiIyLjEuODYifQABRwGM\nAhsiAUkBjAIcBhsgGyEbHBsdGx8bHgIxAYwCHAEYHgIuAYwCGCoCMAKkASQJBucBF64CMAKkASQJ\nBucBF7ICMAKkASQJBucBF7gBOQACMgGMAhwDF3UXTxcUAjIBjAIcAxd1F04XFAIyAYwCHAMXdRdQ\nFxQCMQGMAhwDGCkYJxgoAi4BjAIYLAIwAqQBBAnnAR4CMgGMAhwEF2MXOxdTFxQCMgGMAhwDFzsX\nUxcUAi8BjAIaqwIuAYwCGFcCMAKkAQQJ5wEXsgIxAYwCHAEYVgIuAYwCGB8CMAKkASQJBOcBF6MC\nLwGMAhqqAAACAAAJ/CUBCZgmAAAABjmBCAABgQgAAYEIAAGBCAABgQgAAYEIAAAAAARJgQgAAYEI\nAAGBCAABgQgAAQACAQWZIE2JoATMMwGBoATsM08RhDQAAgEBBpEgAZEgUIGgBKA0URHANAEAAgEI\nmSBSiaAE4DQBgaAEgDVUEZg1AQACAQmZIFWJoASwNQGBoATQNVcR6DUAAAABW4EIAAAAAAFcgQgA\nAAAAAV2BCAAKAAcACgkBCQEJAQkBGQEZARkBGQEZARleiYAExD0BCaw+AQnsPgEJrD8BCfw8AQns\nPwEJ0DwAAAECZYGABIQ4ZgHQNwEB7DcBAwMIFBkVEQEBAQFoiYAEjDsBgYAErDsBgYAE2DtrAZw4\nAQH0OwEBsDgBAaA5AQHkOQEBuDoBAeg4AQGsPAABAQEjkSChAYGABOBEogEB2EMAAwEBJREBEQER\npQGBgATkRaYBAYhGAgAHACgJAQmnAYGABPBGAQmIRwEJ5EcBCdBRAQnQUwEJrFUBCdBMAAEBBwMB\nMYGABIAsMgGAKAEB3CYBAfQmAQGYKgEBjCkBAYwrAQGcLAAAAQI/gYAE+C5AAYgtAgGcLQABAQUE\nAUOBgAS8MkQBnC8BAbAwAQG0LwEB2DIBAawxAAEBARiRIHOBoAT0QnQRkEMAAQEBJJEgowGBgAT8\nRKQBAZhFAAABAliBgASANlkBmDYBAfg2BB4eHx8CHx8AAAIAAAAdQgAAJEIAAAEAAAA3QgAAAgAA\nAEBCAABHQgAAAgAAAEBCAABTQgAAAgAAAEBCAABfQgAAAQAAAGtCAAABAAAAbkIAAAEAAAB7QgAA\nAQAAAIhCAAABAAAAlUIAAAMAAACiQgAAqUIAALNCAAABAAAAwkIAAAIAAADPQgAAqUIAAAIAAADW\nQgAA3UIAAAEAAADoQgAAAgAAAPFCAAD4QgAAAgAAAARDAACpQgAAAgAAAEBCAACpQgAAKEUAAAAA\nAAAAAAAAAAAAADRFAAAAAAAAAAAAAAAAAAA8RQAAAAAAAAAAAAAAAAAASEUAAAAAAAAAAAAAAAAA\nAFRFAAAAAAAAAAAAAAAAAACARQAAAwAAAAEAAAAAAAAAEAAAAGhFAAARAAAAcEUAABIAAAB4RQAA\nYgAAAGBFAACIRQAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAABQAAACYRQAAoEUAAAAAAAAA\nAAAAAAAAAKxFAAAAAAAAAAAAAAAAAAC4RQAAAAAAAAAAAAAAAAAAwEUAAAAAAAAAAAAAAAAAAMxF\nAAAAAAAAAAAAAAAAAADYRQAAAAAAAAAAAAAAAAAAEQAAAAAAAAABAAAAAAAAAAEAAAAYAQAAcAAA\nAAIAAABeAAAA0AQAAAMAAAA/AAAASAYAAAQAAAAqAAAAPAkAAAUAAACuAAAAjAoAAAYAAAAYAAAA\n/A8AAAEgAABFAAAA/BIAAAMgAAAOAAAACCsAAAEQAAAqAAAAjCsAAAIgAAAYAQAAAC0AAAQgAAAX\nAAAAHUIAAAAgAAAWAAAAC0MAAAUgAAACAAAAHkUAAAMQAAASAAAAKEUAAAYgAAAOAAAA5EUAAAAQ\nAAABAAAA7EYAAA=="

    invoke-static {v0, v2}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B

    move-result-object v0

    .line 185
    :try_start_66
    new-instance v2, Ljava/io/FileOutputStream;

    invoke-direct {v2, v1}, Ljava/io/FileOutputStream;-><init>(Ljava/io/File;)V
    :try_end_6b
    .catch Ljava/io/IOException; {:try_start_66 .. :try_end_6b} :catch_8d
    .catchall {:try_start_66 .. :try_end_6b} :catchall_8b

    .line 186
    :try_start_6b
    invoke-virtual {v2, v0}, Ljava/io/FileOutputStream;->write([B)V
    :try_end_6e
    .catch Ljava/io/IOException; {:try_start_6b .. :try_end_6e} :catch_88
    .catchall {:try_start_6b .. :try_end_6e} :catchall_86

    .line 192
    :try_start_6e
    invoke-virtual {v2}, Ljava/io/FileOutputStream;->close()V
    :try_end_71
    .catch Ljava/io/IOException; {:try_start_6e .. :try_end_71} :catch_72

    goto :goto_73

    .line 179
    :catch_72
    move-exception v0

    .line 199
    :goto_73
    iget-object v0, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->shizuku:Ljava/io/File;

    invoke-virtual {v0}, Ljava/io/File;->getAbsolutePath()Ljava/lang/String;

    move-result-object v0

    const/16 v2, 0x302

    invoke-static {v0, v2}, Landroid/system/Os;->chmod(Ljava/lang/String;I)V

    .line 200
    invoke-virtual {v1}, Ljava/io/File;->getAbsolutePath()Ljava/lang/String;

    move-result-object v0

    invoke-static {v0, v2}, Landroid/system/Os;->chmod(Ljava/lang/String;I)V

    return-void

    :catchall_86
    move-exception v0

    goto :goto_90

    :catch_88
    move-exception v0

    move-object v3, v2

    goto :goto_8e

    :catchall_8b
    move-exception v0

    goto :goto_8f

    :catch_8d
    move-exception v0

    .line 188
    :goto_8e
    :try_start_8e
    throw v0
    :try_end_8f
    .catchall {:try_start_8e .. :try_end_8f} :catchall_8b

    .line 200
    :goto_8f
    move-object v2, v3

    .line 188
    :goto_90
    if-eqz v2, :cond_97

    .line 192
    :try_start_92
    invoke-virtual {v2}, Ljava/io/FileOutputStream;->close()V
    :try_end_95
    .catch Ljava/io/IOException; {:try_start_92 .. :try_end_95} :catch_96

    goto :goto_97

    .line 179
    :catch_96
    move-exception v1

    .line 195
    :cond_97
    :goto_97
    throw v0

    :catchall_98
    move-exception v0

    goto :goto_a2

    :catch_9a
    move-exception v0

    move-object v3, v4

    goto :goto_a0

    :catchall_9d
    move-exception v0

    goto :goto_a1

    :catch_9f
    move-exception v0

    .line 172
    :goto_a0
    :try_start_a0
    throw v0
    :try_end_a1
    .catchall {:try_start_a0 .. :try_end_a1} :catchall_9d

    .line 195
    :goto_a1
    move-object v4, v3

    .line 172
    :goto_a2
    if-eqz v4, :cond_a9

    .line 176
    :try_start_a4
    invoke-virtual {v4}, Ljava/io/FileOutputStream;->close()V
    :try_end_a7
    .catch Ljava/io/IOException; {:try_start_a4 .. :try_end_a7} :catch_a8

    goto :goto_a9

    .line 179
    :catch_a8
    move-exception v1

    :cond_a9
    :goto_a9
    throw v0
.end method

.method public run()V
    .registers 8

    .line 47
    new-instance v0, Ljava/io/File;

    invoke-static {}, Lcom/s1243808733/aide/application/App;->getApp()Lcom/s1243808733/aide/application/App;

    move-result-object v1

    invoke-virtual {v1}, Lcom/s1243808733/aide/application/App;->getCacheDir()Ljava/io/File;

    move-result-object v1

    const-string v2, "apkinstall.apk"

    invoke-direct {v0, v1, v2}, Ljava/io/File;-><init>(Ljava/io/File;Ljava/lang/String;)V

    .line 50
    :try_start_f
    iget-object v1, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->apkPath:Ljava/lang/String;

    invoke-virtual {v0}, Ljava/io/File;->getAbsolutePath()Ljava/lang/String;

    move-result-object v2

    invoke-direct {p0, v1, v2}, Lcom/s1243808733/aide/functions/installer/ShellInstall;->copyFile(Ljava/lang/String;Ljava/lang/String;)V

    .line 51
    invoke-virtual {p0}, Lcom/s1243808733/aide/functions/installer/ShellInstall;->initShizuku()V

    .line 52
    invoke-static {}, Ljava/lang/Runtime;->getRuntime()Ljava/lang/Runtime;

    move-result-object v1

    const-string v2, "sh"

    invoke-virtual {v1, v2}, Ljava/lang/Runtime;->exec(Ljava/lang/String;)Ljava/lang/Process;

    move-result-object v1

    .line 53
    invoke-virtual {v1}, Ljava/lang/Process;->getOutputStream()Ljava/io/OutputStream;

    move-result-object v2

    .line 54
    iget-boolean v3, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->isRoot:Z
    :try_end_2b
    .catch Ljava/lang/Exception; {:try_start_f .. :try_end_2b} :catch_1bf

    const-string v4, "\nexit\n"

    if-eqz v3, :cond_58

    .line 55
    :try_start_2f
    const-string v3, "su\n"

    invoke-virtual {v3}, Ljava/lang/String;->getBytes()[B

    move-result-object v3

    invoke-virtual {v2, v3}, Ljava/io/OutputStream;->write([B)V

    .line 56
    new-instance v3, Ljava/lang/StringBuilder;

    const-string v5, "pm install -r "

    invoke-direct {v3, v5}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v0}, Ljava/io/File;->getAbsolutePath()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/String;->getBytes()[B

    move-result-object v0

    invoke-virtual {v2, v0}, Ljava/io/OutputStream;->write([B)V

    .line 57
    invoke-virtual {v2}, Ljava/io/OutputStream;->flush()V

    goto :goto_92

    .line 60
    :cond_58
    new-instance v3, Ljava/lang/StringBuilder;

    const-string v5, "sh "

    invoke-direct {v3, v5}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    iget-object v5, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->shizuku:Ljava/io/File;

    invoke-virtual {v5}, Ljava/io/File;->getAbsolutePath()Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v3

    invoke-virtual {v3}, Ljava/lang/String;->getBytes()[B

    move-result-object v3

    invoke-virtual {v2, v3}, Ljava/io/OutputStream;->write([B)V

    .line 61
    new-instance v3, Ljava/lang/StringBuilder;

    const-string v5, " pm install -r "

    invoke-direct {v3, v5}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v0}, Ljava/io/File;->getAbsolutePath()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/String;->getBytes()[B

    move-result-object v0

    invoke-virtual {v2, v0}, Ljava/io/OutputStream;->write([B)V

    .line 62
    invoke-virtual {v2}, Ljava/io/OutputStream;->flush()V

    .line 64
    :goto_92
    new-instance v0, Ljava/io/InputStreamReader;

    invoke-virtual {v1}, Ljava/lang/Process;->getInputStream()Ljava/io/InputStream;

    move-result-object v2

    invoke-direct {v0, v2}, Ljava/io/InputStreamReader;-><init>(Ljava/io/InputStream;)V

    .line 65
    const/16 v2, 0x400

    new-array v2, v2, [C

    .line 67
    new-instance v3, Ljava/lang/StringBuffer;

    invoke-virtual {v1}, Ljava/lang/Object;->toString()Ljava/lang/String;

    move-result-object v4

    invoke-direct {v3, v4}, Ljava/lang/StringBuffer;-><init>(Ljava/lang/String;)V

    .line 68
    const/16 v4, 0xa

    invoke-virtual {v3, v4}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 69
    :goto_ad
    invoke-virtual {v0, v2}, Ljava/io/InputStreamReader;->read([C)I

    move-result v4

    const/4 v5, -0x1

    const/4 v6, 0x0

    if-eq v4, v5, :cond_b9

    .line 70
    invoke-virtual {v3, v2, v6, v4}, Ljava/lang/StringBuffer;->append([CII)Ljava/lang/StringBuffer;

    goto :goto_ad

    .line 72
    :cond_b9
    invoke-virtual {v3}, Ljava/lang/StringBuffer;->toString()Ljava/lang/String;

    move-result-object v0

    .line 73
    const-string v2, "signatures do not match previously"

    invoke-virtual {v0, v2}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v2
    :try_end_c3
    .catch Ljava/lang/Exception; {:try_start_2f .. :try_end_c3} :catch_1bf

    const-string v3, "Run Problem"

    const-string v4, "运行出现问题"

    if-eqz v2, :cond_e4

    .line 75
    :try_start_c9
    invoke-static {}, Lcom/s1243808733/util/Utils;->isCN()Z

    move-result v0

    if-eqz v0, :cond_d0

    move-object v3, v4

    .line 76
    :cond_d0
    invoke-static {}, Lcom/s1243808733/util/Utils;->isCN()Z

    move-result v0
    :try_end_d4
    .catch Ljava/lang/Exception; {:try_start_c9 .. :try_end_d4} :catch_1bf

    if-eqz v0, :cond_d9

    const-string v0, "该应用安装失败了，签名和已安装的不一致(需要卸载已安装的)"

    goto :goto_db

    :cond_d9
    const-string v0, "The app was not installed due the signature is error"

    .line 77
    :goto_db
    :try_start_db
    new-instance v1, Lcom/s1243808733/aide/functions/installer/ShellInstall$Error;

    invoke-direct {v1, p0, v3, v0}, Lcom/s1243808733/aide/functions/installer/ShellInstall$Error;-><init>(Lcom/s1243808733/aide/functions/installer/ShellInstall;Ljava/lang/String;Ljava/lang/String;)V

    invoke-static {v1}, Lcom/aide/ui/U;->j6(Ljava/lang/Runnable;)Z

    return-void

    .line 79
    :cond_e4
    const-string v2, "INSTALL_FAILED_VERSION_DOWNGRADE"

    invoke-virtual {v0, v2}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v2

    if-eqz v2, :cond_107

    .line 81
    invoke-static {}, Lcom/s1243808733/util/Utils;->isCN()Z

    move-result v0

    if-eqz v0, :cond_f3

    move-object v3, v4

    .line 82
    :cond_f3
    invoke-static {}, Lcom/s1243808733/util/Utils;->isCN()Z

    move-result v0
    :try_end_f7
    .catch Ljava/lang/Exception; {:try_start_db .. :try_end_f7} :catch_1bf

    if-eqz v0, :cond_fc

    const-string v0, "该应用安装失败了，不能降级安装(需要卸载已安装的)"

    goto :goto_fe

    :cond_fc
    const-string v0, "The app was not installed due the version is overtop"

    .line 83
    :goto_fe
    :try_start_fe
    new-instance v1, Lcom/s1243808733/aide/functions/installer/ShellInstall$Error;

    invoke-direct {v1, p0, v3, v0}, Lcom/s1243808733/aide/functions/installer/ShellInstall$Error;-><init>(Lcom/s1243808733/aide/functions/installer/ShellInstall;Ljava/lang/String;Ljava/lang/String;)V

    invoke-static {v1}, Lcom/aide/ui/U;->j6(Ljava/lang/Runnable;)Z

    return-void

    .line 87
    :cond_107
    invoke-virtual {v1}, Ljava/lang/Process;->waitFor()I

    move-result v2

    if-nez v2, :cond_19c

    const-string v2, "Failure"

    invoke-virtual {v0, v2}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v2

    if-nez v2, :cond_19c

    .line 88
    invoke-static {}, Lcom/aide/ui/U;->Zo()Landroid/content/Context;

    move-result-object v1

    invoke-virtual {v1}, Landroid/content/Context;->getPackageManager()Landroid/content/pm/PackageManager;

    move-result-object v1
    :try_end_11d
    .catch Ljava/lang/Exception; {:try_start_fe .. :try_end_11d} :catch_1bf

    .line 90
    const/4 v2, 0x0

    :try_start_11e
    iget-object v5, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->packageName:Ljava/lang/String;

    invoke-virtual {v1, v5, v6}, Landroid/content/pm/PackageManager;->getPackageInfo(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;

    move-result-object v5
    :try_end_124
    .catch Landroid/content/pm/PackageManager$NameNotFoundException; {:try_start_11e .. :try_end_124} :catch_125
    .catch Ljava/lang/Exception; {:try_start_11e .. :try_end_124} :catch_1bf

    goto :goto_127

    :catch_125
    move-exception v5

    move-object v5, v2

    .line 92
    :goto_127
    :try_start_127
    iget-object v6, p0, Lcom/s1243808733/aide/functions/installer/ShellInstall;->packageName:Ljava/lang/String;

    invoke-virtual {v1, v6}, Landroid/content/pm/PackageManager;->getLaunchIntentForPackage(Ljava/lang/String;)Landroid/content/Intent;

    move-result-object v1

    if-eqz v1, :cond_150

    .line 94
    invoke-static {}, Lcom/aide/ui/U;->lg()Lcom/aide/ui/MainActivity;

    move-result-object v0

    invoke-static {}, Lcom/s1243808733/util/Utils;->getApp()Landroid/app/Application;

    move-result-object v3

    const v4, 0x7f0d06ac

    invoke-virtual {v3, v4}, Landroid/app/Application;->getString(I)Ljava/lang/String;

    move-result-object v3

    new-instance v4, Lcom/s1243808733/aide/functions/installer/ShellInstall$1;

    invoke-direct {v4, p0}, Lcom/s1243808733/aide/functions/installer/ShellInstall$1;-><init>(Lcom/s1243808733/aide/functions/installer/ShellInstall;)V

    invoke-static {v0, v3, v4, v2}, Lcom/aide/ui/U;->j6(Landroid/app/Activity;Ljava/lang/String;Ljava/lang/Runnable;Ljava/lang/Runnable;)V
    :try_end_146
    .catch Ljava/lang/Exception; {:try_start_127 .. :try_end_146} :catch_1bf

    .line 106
    :try_start_146
    invoke-static {}, Lcom/aide/ui/U;->Zo()Landroid/content/Context;

    move-result-object v0

    invoke-virtual {v0, v1}, Landroid/content/Context;->startActivity(Landroid/content/Intent;)V
    :try_end_14d
    .catch Ljava/lang/Exception; {:try_start_146 .. :try_end_14d} :catch_14e

    return-void

    :catch_14e
    move-exception v0

    .line 108
    :try_start_14f
    throw v0

    :cond_150
    if-nez v5, :cond_181

    .line 112
    invoke-static {}, Lcom/s1243808733/util/Utils;->isCN()Z

    move-result v1

    if-eqz v1, :cond_159

    move-object v3, v4

    .line 113
    :cond_159
    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    invoke-static {}, Lcom/s1243808733/util/Utils;->isCN()Z

    move-result v2
    :try_end_162
    .catch Ljava/lang/Exception; {:try_start_14f .. :try_end_162} :catch_1bf

    if-eqz v2, :cond_167

    const-string v2, "该应用安装失败了"

    goto :goto_169

    :cond_167
    const-string v2, "The app was not installed."

    :goto_169
    :try_start_169
    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    const-string v2, "\n"

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v1, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    .line 114
    new-instance v1, Lcom/s1243808733/aide/functions/installer/ShellInstall$Error;

    invoke-direct {v1, p0, v3, v0}, Lcom/s1243808733/aide/functions/installer/ShellInstall$Error;-><init>(Lcom/s1243808733/aide/functions/installer/ShellInstall;Ljava/lang/String;Ljava/lang/String;)V

    invoke-static {v1}, Lcom/aide/ui/U;->j6(Ljava/lang/Runnable;)Z

    return-void

    .line 117
    :cond_181
    invoke-static {}, Lcom/s1243808733/util/Utils;->isCN()Z

    move-result v0

    if-eqz v0, :cond_188

    move-object v3, v4

    .line 118
    :cond_188
    invoke-static {}, Lcom/s1243808733/util/Utils;->isCN()Z

    move-result v0
    :try_end_18c
    .catch Ljava/lang/Exception; {:try_start_169 .. :try_end_18c} :catch_1bf

    if-eqz v0, :cond_191

    const-string v0, "该应用已成功安装，但在安装包中找不到启动意图"

    goto :goto_193

    :cond_191
    const-string v0, "The App has been installed successfully but no launch intent was found in the manifest."

    .line 119
    :goto_193
    :try_start_193
    new-instance v1, Lcom/s1243808733/aide/functions/installer/ShellInstall$Error;

    invoke-direct {v1, p0, v3, v0}, Lcom/s1243808733/aide/functions/installer/ShellInstall$Error;-><init>(Lcom/s1243808733/aide/functions/installer/ShellInstall;Ljava/lang/String;Ljava/lang/String;)V

    invoke-static {v1}, Lcom/aide/ui/U;->j6(Ljava/lang/Runnable;)Z

    return-void

    .line 123
    :cond_19c
    new-instance v2, Ljava/lang/RuntimeException;

    new-instance v3, Ljava/lang/StringBuilder;

    invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V

    const-string v4, "waitFor = "

    invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/Process;->waitFor()I

    move-result v1

    invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    const-string v1, "\noutput:"

    invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-direct {v2, v0}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw v2
    :try_end_1bf
    .catch Ljava/lang/Exception; {:try_start_193 .. :try_end_1bf} :catch_1bf

    :catch_1bf
    move-exception v0

    .line 126
    invoke-virtual {v0}, Ljava/lang/Exception;->printStackTrace()V

    .line 127
    new-instance v1, Lcom/s1243808733/aide/functions/installer/ShellInstall$2;

    invoke-direct {v1, p0, v0}, Lcom/s1243808733/aide/functions/installer/ShellInstall$2;-><init>(Lcom/s1243808733/aide/functions/installer/ShellInstall;Ljava/lang/Exception;)V

    invoke-static {v1}, Lcom/aide/ui/U;->j6(Ljava/lang/Runnable;)Z

    return-void
.end method
